version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: daptin/daptin
    ports:
      - "8080:8080"
    restart: always
    environment:
      DAPTIN_PORT: "8080"
      DAPTIN_DB_TYPE: "postgres"
      DAPTIN_DB_CONNECTION_STRING: "host=db port=5432 user=postgres password=password dbname=postgres sslmode=disable"
    depends_on:
      - db
